{
 "title": "Agreements Lifecycle",
 "description": "Agreements Lifefcycle",
 "tags": [ "Edge" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Agreements Lifecycle",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_inception_time*1000"
    },
    {
     "expr": "postgres_agbot_agreement_creation_time*1000"
    },
    {
     "expr": "postgres_agbot_agreement_finalized_time*1000"
    }
   ]
  },
  {
   "title": "Agreements Lifecycle",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_inception_time*1000"
    },
    {
     "expr": "postgres_agbot_agreement_creation_time*1000"
    },
    {
     "expr": "postgres_agbot_agreement_finalized_time*1000"
    },
    {
     "expr": "postgres_agbot_agreement_delta_time"
    }
   ]
  },
  {
   "title": "Flapping",
   "type": "gauge",
   "description": "Agreements without finalized time",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count(postgres_agbot_agreement_finalized_time_null)"
    }
   ]
  },
  {
   "title": "Agreement Finalized Time",
   "type": "table",
   "description": "Agreement finalized time",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_finalized_time_null"
    }
   ]
  },
  {
   "title": "Agreement Inception Time",
   "type": "table",
   "description": "Agreement inception time",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_inception_time*1000"
    }
   ]
  },
  {
   "title": "Agreement Creation Time",
   "type": "table",
   "description": "Agbot Agreement creation time",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 19 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_creation_time*1000"
    }
   ]
  },
  {
   "title": "Agreements",
   "type": "table",
   "description": "Agreement IDs",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_creation_time"
    }
   ]
  },
  {
   "title": "Agreement - Service IDs",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 27 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_service_id"
    }
   ]
  }
 ]
}