{
 "title": "Agbot",
 "description": "Agbot Data",
 "tags": [ "Edge" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Agreements",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_creation_time*1000"
    },
    {
     "expr": "postgres_agbot_agreement_finalized_time*1000"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "go_info" }
   ]
  },
  {
   "title": "Agreement-Creation-Time",
   "type": "table",
   "description": "Agbot Agreement creation time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_creation_time*1000"
    }
   ]
  },
  {
   "title": "Agreement-finalized-time",
   "type": "table",
   "description": "Agreement finalized time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "postgres_agbot_agreement_finalized_time*1000"
    }
   ]
  }
 ]
}