# A collector defining standard metrics for postgres SQL Server.
#
# It is required that the SQL Server user has the following permissions:
#
#   GRANT VIEW ANY DEFINITION TO
#   GRANT VIEW SERVER STATE TO
#
collector_name: postgres_standard

# Similar to global.min_interval, but applies to the queries defined by this collector only.
#min_interval: 0s

metrics:
  - metric_name: postgres_agbot_agreement_creation_time
    type: gauge
    help: 'Agreement:: agreement_creation_time'
    key_labels:
      - agreement_id
    value_label: agreement_creation_time
    values:
      - agbot_agreement_creation_time
    query_ref: postgres_agbot_agreement_creation_time
    
  - metric_name: postgres_agbot_agreement_finalized_time
    type: gauge
    help: 'Agreement:: agreement_finalized_time'
    key_labels:
      - agreement_id
    value_label: agreement_finalized_time
    values:
      - agbot_agreement_finalized_time
    query_ref: postgres_agbot_agreement_finalized_time
       
queries:
  # Populates `postgres_agbot_agreement_creation_time`,.
  - query_name: postgres_agbot_agreement_creation_time 
    query: |
      SELECT
        agreement::jsonb ->> 'agreement_creation_time' as agbot_agreement_creation_time,
        "agreement_id"  as agreement_id
      FROM public.agreements
      
    # Populates `postgres_agbot_agreement_finalized_time`,.
  - query_name: postgres_agbot_agreement_finalized_time 
    query: |
      SELECT  
        agreement::jsonb ->> 'agreement_finalized_time' as agbot_agreement_finalized_time,
        "agreement_id"  as agreement_id
      FROM public.agreements
